### ISSUE TITLE
install-linuxcontainers.sh breaks for some old Android versions (only 4.1/4.0?)

### ISSUE THREAD

**Issue by guillaume-d** [green-green-avk/AnotherTerm-scripts#1]
install-linuxcontainers.sh as used by https://green-green-avk.github.io/AnotherTerm-docs/installing-linux-under-proot.html#main_content breaks for old versions of Android that lack `grep` and `rm -f` (sic!), like 4.1.2 (tested) and probably 4.0 too (untested).

[Also the installation code snippet as a whole fails too here on Android 4.1.2, see green-green-avk/AnotherTerm#7.]

An informal fix for install-linuxcontainers.sh (neither patch nor PR) follows:
1. add the following function definition (I tried to use compact formatting as you do, also debug and test code are still there but commented out):
```bash
echo_prefixed_lines() {
local E
#>&2 echo 1$1;
E=1
while read -r l; do
#>&2 echo $l
case $l in
$1*) echo $l; E=0;;
*) ;;
esac
done
return $E
}

#{ echo aaa; echo b; echo aaab; echo c ;} | echo_prefixed_lines aaa
#exit 666
```
2. replace the `grep -e "^$DISTRO;$RELEASE;$(to_lco_arch `"$1");default;"`` call with `echo_prefixed_lines "$DISTRO;$RELEASE;$(to_lco_arch "$1");default;"` (should have equivalent semantics)
3. replace `rm -rf` [...] with `rm -r` [...] `|| true` (because of `set -e`; if the removal fails for other reasons than an existing file, the following `ln -s` will most probably also fails anyway, so this should not mask any errors)

**Comment by green-green-avk** [comment]
Thank you for your effort. Fixed almost as you have suggested. Great job!
Please, confirm.

**Comment by guillaume-d** [comment]
Works fine now, thanks! 👍
